package traffic_light.IDiagMessage

const UInt32 MaxLogMessageSize = 128;
const UInt32 MaxLogMessageCount = 1;

typedef sequence<UInt8, MaxLogMessageSize> MsgString;
struct DiagnosticMessage {
    UInt32 code;
    MsgString message;
}

interface {
    Write(in DiagnosticMessage inMessage);
}